[project]
dependencies = ["content-hub"]
name = "root"
requires-python = ">=3.14"
version = "0.0.0"

[tool.uv.sources]
"content-hub" = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.poe]
executor = "uv"

[tool.poe.tasks.ws]
cmd = "poe ${task}"
cwd = "packages/${workspace}"

[[tool.poe.tasks.ws.args]]
name = "workspace"
positional = true

[[tool.poe.tasks.ws.args]]
name = "task"
positional = true

[dependency-groups]
dev = [
    "basedpyright>=1.39.6",
    "poethepoet>=0.46.0",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.14",
]
